$ErrorActionPreference = 'Stop'

$root = Join-Path $PSScriptRoot '..'
$skill = Get-Content -LiteralPath (Join-Path $root 'SKILL.md') -Raw
$brief = Get-Content -LiteralPath (Join-Path $root 'audit-brief.md') -Raw

# Closed vocabulary: changing a glyph, dropping yellow polish, or adding a fifth value
# must fail the worker contract rather than producing incomparable audit results.
$grades = '🟩|🟨|🟧|🟥'
$expectedResultSchema = "`"grades`": { `"reach`": `"$grades`", `"impl`": `"$grades`", `"correctness`": `"$grades`", `"utility`": `"$grades`" }"

if ($brief -notmatch [regex]::Escape($expectedResultSchema)) {
    throw 'Worker result grades must use the closed four-glyph vocabulary on every axis.'
}

if ($skill -notmatch [regex]::Escape('Every worker result uses the closed grade vocabulary: 🟩, 🟨, 🟧, 🟥.')) {
    throw 'Skill must require the same closed grade vocabulary as the worker result.'
}

# The controller, not a routed reference, owns every executable output decision.
foreach ($needle in @(
    '🟥 Broken, 🟧 Reliability,',
    'Utility uses the lifecycle scale:',
    '<vault>\Claude\SkillAudits\SkillAudit-YYYY-MM-DD.md',
    '# Skill Audit — YYYY-MM-DD',
    '> Generated by audit-skills · <N> owned skills · <S> runtime surfaces',
    'Skill | Reach | Impl | Correctness | Utility | Top issue',
    'Skill | Disposition | Confidence | Evidence',
    'exact evidence',
    'precise unapplied fix',
    'impact <h/m/l> · effort <l/m/h>',
    'In chat return only the verdict, scorecard, top fixes, and report path'
)) {
    if ($skill -notmatch [regex]::Escape($needle)) {
        throw "Controller output contract is missing: $needle"
    }
}
foreach ($section in 'Verdict', 'Broken', 'Reliability', 'Polish', 'Cross-skill', 'Lifecycle recommendations', 'Trend since <date>', 'Prioritized fixes') {
    if ($skill -notmatch [regex]::Escape($section)) {
        throw "Controller output contract is missing its section: $section"
    }
}

'audit-skills grade schema OK'
